
###########
## site.url, site.title

url:   'http://openfootball.github.io'
title: 'football.db - Open Football Data'


########
# more settings

## markdown: redcarpet
markdown: kramdown


exclude: ['README.md']

safe: true
lsi: false

